spring.application.name=PersonalBudgetApplication

spring.datasource.url=jdbc:mysql://localhost:3306/PersonalBudgetApplicationV2_DB
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

